shop/urls.py
from django.urls import path, include
import django.contrib.auth.urls
from . import views
from shop.views import products, customers, orders, basket, general

app_name = 'shop'

# the empty path '' becomes the 'home page
urlpatterns = [
        path('', views.products.product_list, name='product_list'),
        path('accounts/', include('django.contrib.auth.urls')),
        path('basket_add/<int:product_id>/', views.basket.basket_add, name ='basket_add'),
        path('basket_remove/<int:product_id>/', views.basket.basket_remove, name ='basket_remove'),
        path('basket_detail/', views.basket.basket_detail, name ='basket_detail'),
        path('signup/', views.general.signup, name='signup'),
        path('dashboard/', views.general.dashboard, name='dashboard'),
        path('customer_list', views.customers.customer_list, name='customer_list'),
        path('customer/<int:id>/', views.customers.customer_detail, name= 'customer_detail'),
        path('order_list/', views.orders.order_list, name='order_list'),
        path('order/<int:id>/', views.orders.order_detail, name= 'order_detail'),
        path('payment/', views.general.payment, name ='payment'),
        path('product_list/', views.products.product_list, name='product_list'),
        path('product/<int:id>/', views.products.product_detail, name= 'product_detail'),
        path('product_new/', views.products.product_new, name= 'product_new'),
        path('product/<int:id>/edit/', views.products.product_edit, name= 'product_edit'),
        path('product/<int:id>/delete/', views.products.product_delete, name= 'product_delete'),
        path('purchase/', views.general.purchase, name ='purchase'),
        ]

shopping/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls',  namespace='shop')),
    path('', RedirectView.as_view(url='')),
]

shop/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Cart(models.Model):
    product = models.ForeignKey('shop.Product', on_delete=models.CASCADE, related_name='carts')
    quantity = models.IntegerField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.product},{self.quantity},{self.created_date}'

# switch customer to user so that we can use Django's componenents
# https://blog.crunchydata.com/blog/extending-djangos-user-model-with-onetoonefield 
# https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html#onetoone
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True,)
    address = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.email}, {self.address}'

    class Meta:
        db_table = 'customer'

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Customer.objects.create(user=instance)
    
    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.customer.save()

class LineItem(models.Model):
    quantity = models.IntegerField()
    product = models.ForeignKey('shop.Product', on_delete=models.CASCADE)
    cart = models.ForeignKey('shop.Cart', on_delete=models.CASCADE)
    order = models.ForeignKey('shop.Order', on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.quantity},{self.product},{self.cart},{self.order},{self.created_date}'

class Order(models.Model):
    customer = models.ForeignKey('shop.Customer', on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.customer},{self.created_date}'

class Product(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    # use decimal instead of float to avoid rounding errors
    # always use decimal for money values
    price = models.DecimalField(max_digits=4, decimal_places=2) 
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name},{self.price},{self.created_date}'

shop/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Product

class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30)
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=50)
    address = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 
        'address', 'first_name', 'last_name', )

class ProductForm (forms.ModelForm):
    name= forms.CharField(max_length=200)

    class Meta:
        model = Product
        fields = ('name','price',)

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class BasketAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

shop/views/basket.py
from decimal import Decimal
from django.conf import settings
from django.shortcuts import redirect, render, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from shop.forms import BasketAddProductForm 

class Basket(object):
    # a data transfer object to shift items from cart to page
    # inspired by Django 3 by Example (2020) by Antonio Mele
    # https://github.com/PacktPublishing/Django-3-by-Example/
    
    def __init__(self, request):
        self.session = request.session
        basket = self.session.get(settings.BASKET_SESSION_ID)
        if not basket:
            # save an empty basket in the session
            basket = self.session[settings.BASKET_SESSION_ID] = {}
        self.basket = basket

    def __iter__(self):
        """
        Iterate over the items in the basket and get the products
        from the database.
        """
        print(f'basket: { self.basket }')
        product_ids = self.basket.keys()
        # get the product objects and add them to the basket
        products = Product.objects.filter(id__in=product_ids)

        basket = self.basket.copy()
        for product in products:
            basket[str(product.id)]['product'] = product
            basket[str(product.id)]['product_id'] = product.id

        for item in basket.values():
            item['price'] = Decimal(item['price'])
            item['total_price'] = item['price'] * item['quantity']
            yield item

    def __len__(self):
        """
        Count all items in the basket.
        """
        return sum(item['quantity'] for item in self.basket.values())

    def add(self, product, quantity=1, override_quantity=False):
        """
        Add a product to the basket or update its quantity.
        """
        product_id = str(product.id)
        if product_id not in self.basket:
            self.basket[product_id] = {'quantity': 0,
                                      'price': str(product.price)}
        if override_quantity:
            self.basket[product_id]['quantity'] = quantity
        else:
            self.basket[product_id]['quantity'] += quantity
        self.save()

    def save(self):
        # mark the session as "modified" to make sure it gets saved
        self.session.modified = True

    def remove(self, product):
        """
        Remove a product from the basket.
        """
        product_id = str(product.id)
        if product_id in self.basket:
            del self.basket[product_id]
            self.save()

    def clear(self):
        # remove basket from session
        del self.session[settings.BASKET_SESSION_ID]
        self.save()

    def get_total_price(self):
        return sum(Decimal(item['price']) * item['quantity'] for item in self.basket.values())


@require_POST
def basket_add(request, product_id):
    basket = Basket(request)
    product = get_object_or_404(Product, id=product_id)
    form = BasketAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        basket.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('shop:basket_detail')

@require_POST
def basket_remove(request, product_id):
    basket = Basket(request)
    product = get_object_or_404(Product, id=product_id)
    basket.remove(product)
    return redirect('shop:basket_detail')

def basket_detail(request):
    basket = Basket(request)
    for item in basket:
        item['update_quantity_form'] = BasketAddProductForm(initial={'quantity': item['quantity'],
                                                                   'override': True})
    return render(request, 'shop/basket.html', {'basket': basket})

shop/views/customers.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

@login_required
def customer_list(request):
    user = request.user
    if user.is_authenticated & user.is_staff:
        users = User.objects.all()
        return render(request, 'shop/customer_list.html', {'users' : users})
    else:
        return redirect('shop:login')

@login_required
def customer_detail(request, id):
    user = get_object_or_404(User, id=id)
    return render(request, 'shop/customer_detail.html', {'user' : user})

shop/views/general.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from shop.models import Cart, Customer, LineItem, Order, Product
from shop.forms import SignUpForm
from shop.views.basket import Basket

def signup(request):
    form = SignUpForm(request.POST)
    if form.is_valid():
        user = form.save()
        user.refresh_from_db()
        user.customer.first_name = form.cleaned_data.get('first_name')
        user.customer.last_name = form.cleaned_data.get('last_name')
        user.customer.address = form.cleaned_data.get('address')
        user.save()
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password= password)
        login(request, user)
        return redirect('/')
    return render(request, 'signup.html', {'form': form})

@login_required
def dashboard(request):
    user = request.user
    if user.is_authenticated & user.is_staff:
        return render(request, 'shop/dashboard.html')
    else:
        return redirect('shop:login')

# save order, clear basket and thank customer
def payment(request):
    basket = Basket(request)
    user = request.user
    customer = get_object_or_404(Customer, user_id=user.id)
    order = Order.objects.create(customer=customer)
    order.refresh_from_db()
    for item in basket:
        product_item = get_object_or_404(Product, id=item['product_id'])
        cart = Cart.objects.create(product = product_item, quantity=item['quantity'])
        cart.refresh_from_db()
        line_item = LineItem.objects.create(quantity=item['quantity'], product=product_item, cart=cart,  order = order)

    basket.clear()
    request.session['deleted'] = 'thanks for your purchase'
    return redirect('shop:product_list' )

def purchase(request):
    if request.user.is_authenticated:
       user = request.user
       basket = Basket(request)
       
       return render(request, 'shop/purchase.html', {'basket': basket, 'user': user})
    else:
        return redirect('shop:login')

shop/views/orders.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from shop.models import LineItem, Order

def order_list(request):
    orders = Order.objects.all()
    return render(request, 'shop/order_list.html', {'orders' : orders})

def order_detail(request, id):
    order = get_object_or_404(Order, id=id)
    customer = order.customer
    user = get_object_or_404(User, id=customer.pk)
    line_items = LineItem.objects.filter(order_id=order.id)
    return render(request, 'shop/order_detail.html', {'order' : order, 'user': user, 'line_items': line_items})

shop/views/products.py
from django.shortcuts import redirect, render, get_object_or_404
from django.utils import timezone
from shop.forms import BasketAddProductForm, ProductForm
from shop.models import Product

def product_list(request):
    products = Product.objects.all()    
    return render(request, 'shop/product_list.html', {'products' : products })

def product_detail(request, id):
    product = get_object_or_404(Product, id=id)
    basket_product_form = BasketAddProductForm()
    return render(request, 'shop/product_detail.html', {'product' : product, 'basket_product_form': basket_product_form })

def product_new(request):
    if request.method=="POST":
        form = ProductForm(request.POST)
        if form.is_valid():
            product = form.save(commit=False)
            product.created_date = timezone.now()
            product.save()
            return redirect('shop:product_detail', id=product.id)
    else:
        form = ProductForm()
    return render(request, 'shop/product_edit.html', {'form': form})

def product_edit(request, id):
    product = get_object_or_404(Product, id=id)
    if request.method=="POST":
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            product = form.save(commit=False)
            product.created_date = timezone.now()
            product.save()
            return redirect('shop:product_detail', id=product.id)
    else:
        form = ProductForm(instance=product)
    return render(request, 'shop/product_edit.html', {'form': form})

def product_delete(request, id):
    product = get_object_or_404(Product, id=id)
    deleted = request.session.get('deleted', 'empty')
    request.session['deleted'] = product.name
    product.delete()
    return redirect('shop:product_list' )

shop/templates/shop/base.html
{% load static %}
<html>
<head>
  <title>Acme Shopping </title>
  <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
  {% if user.is_staff %}
  <p>
  <a href = "{% url 'shop:product_list' %}">Acme Shopping Home</a>
  <a href = "{% url 'shop:dashboard' %}">Dashboard</a> |
  <a href = "{% url 'shop:basket_detail' %}">Basket</a>
  <a href = "{% url 'shop:customer_list' %}">Customers</a> | 
  <a href = "{% url 'shop:order_list' %}">Orders</a> |
  {% else %}
<p> 
    <a href = "{% url 'shop:product_list' %}">Acme Shopping Home</a> |
    <a href = "{% url 'shop:basket_detail' %}">Basket</a>
    {% endif %}
    {% if user.is_authenticated %}
    <a href = "{% url 'shop:logout' %}">Log Out</a> </p>
    {% else %}
    <a href = "{% url 'shop:login' %}">Log In</a> 
    </p>
    {% endif %}

    {% block content %}
    {% endblock %}

</body>
</html>

shop/templates/shop/basket.html
{% extends 'shop/base.html' %}
{% block content %}
    <h1>Acme Shopping: Your Basket</h1>
    
<h2>You have these in your basket:</h2>
 <table>
  {% for item in basket %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{% url 'shop:product_detail' id=product.id %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url 'shop:basket_add' product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <input type="submit" value="Update">
                {% csrf_token %}
              </form>
            </td>
            <td>
              <form action="{% url 'shop:basket_remove' product.id %}" method="post">
                <input type="submit" value="Remove">
                {% csrf_token %}
              </form>
            </td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">${{ basket.get_total_price }}</td>
      </tr>
  </table>
  <p class="text-right">
    <a href="{% url "shop:product_list" %}" class="button
    light">Continue shopping</a>
  </p>
 
   <a href="{% url 'shop:purchase' %}">Purchase</a>
 {% endblock %}

shop/templates/shop/customer_detail.html
{% extends 'shop/base.html' %}
{% block content %}
    <h1>Acme Shopping: Customer Details</h1>
    
    <p>Customer: 
      This is {{ user.first_name }} {{ user.last_name }} who lives at 
      {{user.customer.address}}. You can reach them at {{ user.email }} 
   </p>
  <p>Modify the method to also supply the customer's orders</p>
   
    {% endblock %}

shop/templates/shop/customer_list.html
  {% extends 'shop/base.html' %}
  {% block content %}
    <h1>Customer List</h1>
    
    {% for user in users %}
    <p><b> <a href="{% url 'shop:customer_detail' id=user.pk %}"> {{user.first_name }} {{user.last_name }} </a></b>
      Their username is {{ user.username }} and they live at 
       {{ user.customer.address }}. You can reach them at {{ user.email }} 
    </p>
    {% endfor %}

{% endblock %}

shop/templates/shop/dashboard.html
{% extends 'shop/base.html' %}
{% block content %}
    <h1>Acme Shopping: The Admin Dashboard</h1>
<p>Do something with charts based on orders, and customers. This could be orders per week/month, etc,
    or distribution of your customers, or shops if you have those. You might also do something based on
    most common items sold, or other details from your orders.
</p>

{% endblock %}

shop/templates/shop/order_detail.html
{% extends 'shop/base.html' %}
{% block content %}
    <h1>Acme Shopping: Order Details</h1>
    
    <p>Order: 
      This is order {{ order.id }} for
      {{user.first_name}} {{user.last_name}}. The order was placed on: {{ order.created_date }} 
   </p>
  <p>The order includes these items:</p>
  {% for line_item in line_items %}
  <p>
   Quantity: {{ line_item.quantity}}  Item: {{ line_item.product }}
  </p>
  
  {% endfor %}
   
    {% endblock %}

shop/templates/shop/order_list.html
  {% extends 'shop/base.html' %}
  {% block content %}
    <h1>Order List</h1>
    
    {% for order in orders %}
    <p>This is order <b> <a href="{% url 'shop:order_detail' id=order.id %}">{{order.id }}</a></b> for
       {{order.customer.id}}. The order was placed on: {{ order.created_date }} 
    </p>
    {% endfor %}

    {% endblock %}

shop/templates/shop/product_detail.html
{% extends 'shop/base.html' %}
{% block content %}
    <h1>Acme Shopping: Product Details</h1>
    
    <p>Product {{ product.id }}: <a href="{% url 'shop:product_edit' id=product.id %}">Edit</a>
      This is product {{ product.name }} which costs
      {{product.price}}. The product was added on: {{ product.created_date }} 
   </p>
   <p>
    <form action="{% url 'shop:basket_add' product.id %}" method="post">
      {{ basket_product_form }}
      {% csrf_token %}
      <input type="submit" value="Add to Basket">
    </form>
       </p>
   <p><a href="{% url 'shop:product_delete' id=product.id %}">Delete the product</a></p>
    {% endblock %}
    

shop/templates/shop/product_edit.html
{% extends 'shop/base.html' %}
{% block content %}
    <h1>Acme Shopping: Product Edit</h1>
    <p>Product:
    <form method="POST"> {% csrf_token %}
      {{ form.as_p}}
      <button type="submit" name="submit">Save</button>
   </p>
</form>
    {% endblock %}

shop/templates/shop/product_list.html
  {% extends 'shop/base.html' %}
  {% block content %}
    <h1>Product List</h1>
<p>{{ deleted }} </p>
    <p><a href="{% url 'shop:product_new' %}">Add a new product</a></p>
    {% for product in products %}
    <p><b> <a href="{% url 'shop:product_detail' id=product.id %}">{{product.name }}</a></b>
      This is product {{ product.id }} which costs
       {{product.price}}. The product was added on: {{ product.created_date }} 
    {% endfor %}

    {% endblock %}

shop/templates/shop/purchase.html
{% extends 'shop/base.html' %}
{% block content %}
    <h1>Acme Shopping: Your Order</h1>
    
<h2>You have these in your basket:</h2>
  {% for item in basket %}
    {% with product=item.product %}
 
<p>You put {{product.quantity }} of our <b> {{ product.name }} </b> which each cost {{ item.price }} and cost {{ item.total_price }} for in your basket.</p>
     {% endwith %}
   {% endfor %}
 <p>The total for all of this fun is: {{ basket.get_total_price }} </p>
   <p>
    <form action="/payment/" method="post">
       {% csrf_token %}
       <p>Complete the form to buy this all for yourself</p>
       <input type='text' name='first_name' value="{{user.first_name}}" disabled>
       <input type='text' name='last_name' value="{{user.last_name}}" disabled><br>
       <label for 'payment'>Card Type:</label><input type='text' size=5 name='payment'>
       <input type="number" name="total" value="Total Payment:">
       <input type="submit" value="Payment">
       </form>
       </p>
 {% endblock %}